### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by iamdey** [atoum/atom-plugin#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Debian GNU/Linux
**Thrown From**: [atoum-plugin](https://github.com/atoum/atom-plugin) package, v0.4.1
### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:854

TypeError: path must be a string
    at TypeError (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at AtoumRunner.module.exports.AtoumRunner.start (/home/ABC-OBJECTIF/david.epely/.atom/packages/atoum-plugin/lib/runner.coffee:45:15)
    at AtoumToolbarView.module.exports.AtoumToolbarView.startStop (/home/ABC-OBJECTIF/david.epely/.atom/packages/atoum-plugin/lib/views/toolbar.coffee:25:22)
    at HTMLAnchorElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLAnchorElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLAnchorElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -0:05.8.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:03.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.5.0 atoum-plugin:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "jshint"
    ]
  },
  "atoum-plugin": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
atom-xsltransform, v0.8.0
atoum-plugin, v0.4.1
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
behat-atom, v0.1.2
clipboard-plus, v0.5.1
color-picker, v2.0.13
editorconfig, v1.2.2
linter, v1.11.3
linter-eslint, v5.2.4
minimap, v4.16.2
node-debugger, v1.3.0
node-resolver, v1.0.1
php-twig, v4.0.0
project-manager, v2.6.5
symfony-snippets, v0.3.0
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by Spy-Seth** [comment]
I've the same issue.

**Comment by armandabric** [comment]
I've the issue. If you need more info do not hesitate to ask.

**Comment by armandabric** [comment]
Running a single file is working again :+1:

**Comment by jubianchi** [comment]
@Spy-Seth yay! it should work with single file and directories ;) If not, let m know so I can reopen this issue.

Thanks!

**Comment by iamdey** [comment]
nice job. thx
