### ISSUE TITLE
Uncaught TypeError: Cannot read property 'diag' of null

### ISSUE THREAD

**Issue by armandabric** [atoum/atom-plugin#6]
1. Select a directory in the tree view
2. Trigger the atoum `Run directory` command

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [atoum-plugin](https://github.com/atoum/atom-plugin) package, v0.5.0
### Stack Trace

Uncaught TypeError: Cannot read property 'diag' of null

```
At /Users/spy-seth/.atom/packages/atoum-plugin/lib/parser.coffee:80

TypeError: Cannot read property 'diag' of null
  at AtoumParser.module.exports.AtoumParser.parseLine (/Users/spy-seth/.atom/packages/atoum-plugin/lib/parser.coffee:80:34)
  at /Users/spy-seth/.atom/packages/atoum-plugin/lib/parser.coffee:42:33
  at Array.forEach (native)
  at AtoumParser.module.exports.AtoumParser.parse (/Users/spy-seth/.atom/packages/atoum-plugin/lib/parser.coffee:42:14)
  at AtoumParser.module.exports.AtoumParser.runnerDidProduceOutput (/Users/spy-seth/.atom/packages/atoum-plugin/lib/parser.coffee:29:10)
  at /Users/spy-seth/.atom/packages/atoum-plugin/lib/panel.coffee:37:21
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at AtoumRunner.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at /Users/spy-seth/.atom/packages/atoum-plugin/lib/runner.coffee:43:26
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:523:20)

```
### Commands

```
     -1:22.4.0 command-palette:toggle (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
  3x -1:18.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:17.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:17.9.0 atoum-plugin:run-current-file (atom-text-editor.editor.enable-nuclide-find-references)
     -0:53.1.0 core:move-left (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -0:52.8.0 core:backspace (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -0:50.6.0 core:save (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -0:37.7.0 core:undo (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -0:36.6.0 core:save (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -0:22 command-palette:toggle (atom-text-editor.editor.enable-nuclide-find-references)
     -0:15.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:15.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:10.8.0 command-palette:toggle (div.nuclide-file-tree.focusable-panel.tree-view)
  2x -0:08.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.9.0 atoum-plugin:run-directory (div.nuclide-file-tree.focusable-panel.tree-view)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "php-cs-fixer",
      "tree-view",
      "autocomplete-modules",
      "linter"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "git-plus"
    ],
    "projectHome": "/Users/spy-seth/workspace",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "atoum-plugin": {
    "failIfVoidMethod": true,
    "phpPath": "/usr/local/bin/php"
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.21
atoum-plugin, v0.5.0
docblockr, v0.7.3
editorconfig, v1.2.4
highlight-selected, v0.11.1
language-apache, v1.4.0
language-docker, v1.1.6
language-gherkin, v1.0.3
language-nginx, v0.6.1
linter-eslint, v5.2.7
linter-jsonlint, v1.1.4
linter-less, v2.3.3
linter-php, v1.1.6
nuclide, v0.111.0
php-composer-completion, v0.3.4
php-getters-setters, v0.5.5
php-twig, v4.0.0
pretty-json, v0.4.1
project-manager, v2.7.3
react, v0.14.1
sync-settings, v0.6.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by jubianchi** [comment]
sorry for that, I'll fix it!
